services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp #
      - 30096:30096/tcp # Transmission WebUI
      - 6881:6881
      - 6881:6881/udp
#    volumes:
#      - ${VPN_PROFILE_PATH}:/gluetun/custom.ovpn:ro
    environment:
      - UPDATER_PERIOD=24h
      - BLOCK_MALICIOUS=off
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:30096/api/v2/app/setPreferences 2>&1'
      - VPN_TYPE=${VPN_TYPE}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${VPN_USER_NAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=568
      - PGID=3010
      - TZ=Etc/UTC
      - WEBUI_PORT=30096
    volumes:
      - .:/config
      - ${DOWNLOADS_PATH}:/data/torrents #optional
    #    ports:
    #      - 8080:8080
    #      - 6881:6881
    #      - 6881:6881/udp
