services:
  lldap:
    image: lldap/lldap:2026-01-06
    restart: unless-stopped
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      # - "6360:6360"
      # For the web front-end
      # - "37170:17170"
    volumes:
      - "./lldap_data:/data"
    networks:
      - internal
      - traefik
    environment:
      #- UID=####
      #- GID=####
      - TZ=Europe/Paris
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=dc=anneraud,dc=fr
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS} # If the password contains '$', escape it (e.g. Pas$$word sets Pas$word)
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      #- LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
      - LLDAP_DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
      # If using SMTP, set the following variables
      # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      # - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
      # - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp provider's documentation for this setting
      # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
      # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
      # - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap.rule=Host(`ldap.anneraud.fr`)
      - traefik.http.routers.lldap.entrypoints=web-secure
      - traefik.http.routers.lldap.tls=true
      - traefik.http.routers.lldap.tls.certresolver=letsencrypt
      - traefik.http.services.lldap.loadbalancer.server.port=17170
      - traefik.http.services.lldap.loadbalancer.server.scheme=http

      - traefik.tcp.routers.lldaps.rule=HostSNI(`ldap.anneraud.fr`)
      - traefik.tcp.routers.lldaps.entrypoints=ldaps
      - traefik.tcp.routers.lldaps.tls=true
      - traefik.tcp.routers.lldaps.tls.certresolver=letsencrypt
      - traefik.tcp.services.lldaps.loadbalancer.server.port=3890

  database:
    image: postgres:18
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - "./postgres_data:/var/lib/postgresql"

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    #user: postgres:postgres # Optional: see below
    volumes:
      - ./postgres_backup:/backups
    networks:
      - internal
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

networks:
  internal:
  traefik:
    external: true
