services:
  docmost:
    image: docmost/docmost:0.24
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "30101:3000"
    restart: unless-stopped
    volumes:
      - ./Storage:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./Postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    volumes:
      - ./Redis_data:/data

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    #user: postgres:postgres # Optional: see below
    volumes:
      - ./Postgres_backup:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      #  - DATABASE_PASSWORD_FILE=/run/secrets/db_password <-- alternative for DATABASE_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
