services:
  traefik:
    image: "traefik:v3.6"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    environment:
      - TZ=Europe/Paris
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--providers.file.directory=/etc/traefik/dynamic"

      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entryPoint.permanent=true"

      - "--entryPoints.web-secure.address=:443"
      - "--entryPoints.web-secure.http.tls=true"

      - "--entryPoints.web-secure-federation.address=:8448"
      - "--entryPoints.web-secure-federation.http.tls=true"
      
      - "--entryPoints.ldaps.address=:636"

      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.email=alix@anneraud.fr" # replace with your actual email
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      #- "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=10"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8448:8448" # Matrix federation port
      - "636:636" # LDAPS port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Add the following volumes
      - "./certificates/:/certs:ro"
      - "./dynamic:/etc/traefik/dynamic:ro"
        # ...Existing volumes...
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.luxembourg.anneraud.fr`)"
      - "traefik.http.routers.dashboard.entrypoints=web-secure"
      - "traefik.http.routers.dashboard.service=api@internal"
      # Add the following label
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

      # Allowlist middleware configuration
      - "traefik.http.middlewares.internal-allowlist.ipallowlist.sourcerange=192.168.0.0/24,100.64.0.0/24,fd00::/8,172.16.0.0/12"
      
      # Apply the middleware to the dashboard router
      - "traefik.http.routers.dashboard.middlewares=internal-allowlist@docker"

networks:
  traefik:
    name: traefik
